version: '3'
services:
  webapp:
    build:
      context: ./frontend
    ports:
      - "80:80"
    deploy:
      restart_policy:
        condition: on-failure
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure